PUT http://localhost:3001/api/persons/681a3bd643bd43123a8c6c30
Content-Type: application/json

{
    "name": "Harry Potter",
    "number": "000-000000"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "He",
    "number": "343678"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "135-24680"
}


###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Ron Weasley",
    "number": "001-98765"
}